/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.form;

import controller.Controller;
import domain.Clan;
import domain.Clanarina;
import domain.IzmenaClanarina;
import domain.Polaganje;
import domain.Prisustvo;
import java.awt.Font;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;
import view.components.ListModelPrisustva;
import view.components.TableModelClanarine;
import view.components.TableModelClanovi;
import view.components.TableModelPolaganja;

/**
 *
 * @author Sara
 */
public class FrmMain extends javax.swing.JFrame {
    
    private List<Clanarina> zaEdit;
    private List<Clanarina> zaDelete;
    private List<Clanarina> zaAdd;

    /**
     * Creates new form MainForm
     */
    public FrmMain() {
        initComponents();
        setLocationRelativeTo(null);
        
        tblClanovi.setModel(new TableModelClanovi());
        listPrisustva.setModel(new ListModelPrisustva());
        tblClanarine.setModel(new TableModelClanarine());
        tblPolaganja.setModel(new TableModelPolaganja());
        
        setHomePnl();
        
        JTableHeader tableHeader = tblPolaganja.getTableHeader();
        Font headerFont = new Font("Segoe UI", Font.BOLD, 18);
        tableHeader.setFont(headerFont);
        
        tableHeader = tblClanarine.getTableHeader();
        tableHeader.setFont(headerFont);
        
        tableHeader = tblClanovi.getTableHeader();
        tableHeader.setFont(headerFont);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new javax.swing.JPanel();
        pnlSideMenu = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnMembers = new javax.swing.JButton();
        btnAttendance = new javax.swing.JButton();
        btnPayments = new javax.swing.JButton();
        btnTests = new javax.swing.JButton();
        pnlRight = new javax.swing.JPanel();
        pnlHome = new javax.swing.JPanel();
        lblFigures = new javax.swing.JLabel();
        pnlAddMember = new javax.swing.JPanel();
        pnlUnosClana = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPrezime = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTelefon = new javax.swing.JTextField();
        txtAdresa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbPol = new javax.swing.JComboBox<>();
        cmbPojas = new javax.swing.JComboBox<>();
        btnDodajClana = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblClanovi = new javax.swing.JTable();
        btnIzmeniClana = new javax.swing.JButton();
        btnObrisiClana = new javax.swing.JButton();
        pnlAttendance = new javax.swing.JPanel();
        pnlUnosPrissustva = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cmbClanPrisustva = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        txtDatumPrisustvovanja = new javax.swing.JTextField();
        btnUnesiPrisustvo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listPrisustva = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        cmbMesecPretraga = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        txtGodinaPretraga = new javax.swing.JTextField();
        btnPretraziPrisustvo = new javax.swing.JButton();
        btnOcistiPretraguPrisustva = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        btnObrisiPrisustvo = new javax.swing.JButton();
        pnlPayments = new javax.swing.JPanel();
        pnlZaduzenjaClana = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        cmbClanClanarine = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblClanarine = new javax.swing.JTable();
        btnIzmeniZaduzenje = new javax.swing.JButton();
        btnObrisiZaduzenje = new javax.swing.JButton();
        pnlUnosZaduzenja = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtIznos = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        txtGodina = new javax.swing.JTextField();
        btnUnosNovogZaduzenja = new javax.swing.JButton();
        btnSacuvajIzmene = new javax.swing.JButton();
        pnlTests = new javax.swing.JPanel();
        pnlPolaganja = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        cmbClanPolaganja = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPolaganja = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        rbPolozenoDa = new javax.swing.JRadioButton();
        rbPolozenoNe = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtDatumPolaganja = new javax.swing.JTextField();
        btnUnesiNovoPolaganje = new javax.swing.JButton();
        cmbPolaganjeZaPojas = new javax.swing.JComboBox<>();
        btnIzmeniPolaganje = new javax.swing.JButton();
        btnObrisiPolaganje = new javax.swing.JButton();
        pnlTop = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Oss!");

        pnlBackground.setBackground(new java.awt.Color(255, 255, 255));

        pnlSideMenu.setBackground(new java.awt.Color(51, 42, 33));
        pnlSideMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(225, 127, 38), 3));

        btnHome.setBackground(new java.awt.Color(59, 56, 54));
        btnHome.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setText("Pocetna");
        btnHome.setBorder(null);
        btnHome.setBorderPainted(false);
        btnHome.setFocusPainted(false);
        btnHome.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnMembers.setBackground(new java.awt.Color(59, 56, 54));
        btnMembers.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        btnMembers.setForeground(new java.awt.Color(255, 255, 255));
        btnMembers.setText("Clanovi");
        btnMembers.setBorder(null);
        btnMembers.setBorderPainted(false);
        btnMembers.setFocusPainted(false);
        btnMembers.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnMembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMembersActionPerformed(evt);
            }
        });

        btnAttendance.setBackground(new java.awt.Color(59, 56, 54));
        btnAttendance.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        btnAttendance.setForeground(new java.awt.Color(255, 255, 255));
        btnAttendance.setText("Prisustva");
        btnAttendance.setBorder(null);
        btnAttendance.setBorderPainted(false);
        btnAttendance.setFocusPainted(false);
        btnAttendance.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttendanceActionPerformed(evt);
            }
        });

        btnPayments.setBackground(new java.awt.Color(59, 56, 54));
        btnPayments.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        btnPayments.setForeground(new java.awt.Color(255, 255, 255));
        btnPayments.setText("Clanarine");
        btnPayments.setBorder(null);
        btnPayments.setBorderPainted(false);
        btnPayments.setFocusPainted(false);
        btnPayments.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnPayments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentsActionPerformed(evt);
            }
        });

        btnTests.setBackground(new java.awt.Color(59, 56, 54));
        btnTests.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        btnTests.setForeground(new java.awt.Color(255, 255, 255));
        btnTests.setText("Polaganja");
        btnTests.setBorder(null);
        btnTests.setBorderPainted(false);
        btnTests.setFocusPainted(false);
        btnTests.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnTests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSideMenuLayout = new javax.swing.GroupLayout(pnlSideMenu);
        pnlSideMenu.setLayout(pnlSideMenuLayout);
        pnlSideMenuLayout.setHorizontalGroup(
            pnlSideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnMembers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAttendance, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
            .addComponent(btnPayments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTests, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlSideMenuLayout.setVerticalGroup(
            pnlSideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSideMenuLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMembers, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAttendance, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPayments, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTests, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(381, Short.MAX_VALUE))
        );

        pnlRight.setBackground(new java.awt.Color(255, 255, 255));

        pnlHome.setBackground(new java.awt.Color(255, 255, 255));

        lblFigures.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/figures.jpg"))); // NOI18N

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(lblFigures)
                .addContainerGap(227, Short.MAX_VALUE))
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(lblFigures)
                .addContainerGap(270, Short.MAX_VALUE))
        );

        pnlAddMember.setBackground(new java.awt.Color(255, 255, 255));

        pnlUnosClana.setBackground(new java.awt.Color(255, 255, 255));
        pnlUnosClana.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Unos novog clana", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 24))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Ime:");

        txtIme.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtIme.setPreferredSize(new java.awt.Dimension(0, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Prezime:");

        txtPrezime.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPrezime.setPreferredSize(new java.awt.Dimension(0, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Pol:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Telefon:");

        txtTelefon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTelefon.setPreferredSize(new java.awt.Dimension(0, 30));

        txtAdresa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtAdresa.setPreferredSize(new java.awt.Dimension(0, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Adresa:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Pojas:");

        cmbPol.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbPol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Muski", "Zenski" }));
        cmbPol.setPreferredSize(new java.awt.Dimension(0, 30));

        cmbPojas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbPojas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Beli", "Plavi", "Ljubicasti", "Braon", "Crni" }));
        cmbPojas.setPreferredSize(new java.awt.Dimension(0, 30));

        btnDodajClana.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDodajClana.setText("Dodaj clana");
        btnDodajClana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajClanaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlUnosClanaLayout = new javax.swing.GroupLayout(pnlUnosClana);
        pnlUnosClana.setLayout(pnlUnosClanaLayout);
        pnlUnosClanaLayout.setHorizontalGroup(
            pnlUnosClanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUnosClanaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUnosClanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(pnlUnosClanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbPojas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtIme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbPol, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTelefon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAdresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(pnlUnosClanaLayout.createSequentialGroup()
                .addGap(456, 456, 456)
                .addComponent(btnDodajClana, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(467, Short.MAX_VALUE))
        );
        pnlUnosClanaLayout.setVerticalGroup(
            pnlUnosClanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUnosClanaLayout.createSequentialGroup()
                .addGroup(pnlUnosClanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlUnosClanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlUnosClanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cmbPol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlUnosClanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlUnosClanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtAdresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlUnosClanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbPojas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnDodajClana)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlUnosClanaLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cmbPojas, cmbPol, txtAdresa, txtIme, txtPrezime, txtTelefon});

        tblClanovi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tblClanovi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblClanovi.setRowHeight(33);
        jScrollPane4.setViewportView(tblClanovi);

        btnIzmeniClana.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnIzmeniClana.setText("Izmeni clana");
        btnIzmeniClana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniClanaActionPerformed(evt);
            }
        });

        btnObrisiClana.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnObrisiClana.setText("Obrisi clana");
        btnObrisiClana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiClanaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAddMemberLayout = new javax.swing.GroupLayout(pnlAddMember);
        pnlAddMember.setLayout(pnlAddMemberLayout);
        pnlAddMemberLayout.setHorizontalGroup(
            pnlAddMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddMemberLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAddMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4)
                    .addComponent(pnlUnosClana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlAddMemberLayout.createSequentialGroup()
                        .addComponent(btnIzmeniClana)
                        .addGap(18, 18, 18)
                        .addComponent(btnObrisiClana)
                        .addGap(0, 857, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlAddMemberLayout.setVerticalGroup(
            pnlAddMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddMemberLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlUnosClana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(pnlAddMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIzmeniClana)
                    .addComponent(btnObrisiClana))
                .addContainerGap())
        );

        pnlAttendance.setBackground(new java.awt.Color(255, 255, 255));
        pnlAttendance.setPreferredSize(new java.awt.Dimension(0, 40));

        pnlUnosPrissustva.setBackground(new java.awt.Color(255, 255, 255));
        pnlUnosPrissustva.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Unos prisustva", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 24))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Clan:");
        jLabel7.setPreferredSize(new java.awt.Dimension(0, 40));

        cmbClanPrisustva.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbClanPrisustva.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbClanPrisustva.setPreferredSize(new java.awt.Dimension(0, 40));
        cmbClanPrisustva.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbClanPrisustvaItemStateChanged(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Datum prisustvovanja:");
        jLabel8.setPreferredSize(new java.awt.Dimension(0, 40));

        txtDatumPrisustvovanja.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtDatumPrisustvovanja.setPreferredSize(new java.awt.Dimension(0, 40));

        btnUnesiPrisustvo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnUnesiPrisustvo.setText("Unsei prisustvo");
        btnUnesiPrisustvo.setPreferredSize(new java.awt.Dimension(96, 33));
        btnUnesiPrisustvo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnesiPrisustvoActionPerformed(evt);
            }
        });

        listPrisustva.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        listPrisustva.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listPrisustva);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pretraga prisustva:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setText("Za mesec:");

        cmbMesecPretraga.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbMesecPretraga.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Januar", "Februar", "Mart", "April", "Maj", "Jun", "Jul", "Avgust", "Septembar", "Oktobar", "Novembar", "Decembar" }));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setText("Za godinu:");

        txtGodinaPretraga.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnPretraziPrisustvo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPretraziPrisustvo.setText("Pretrazi");
        btnPretraziPrisustvo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziPrisustvoActionPerformed(evt);
            }
        });

        btnOcistiPretraguPrisustva.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnOcistiPretraguPrisustva.setText("Ocisti pretagu");
        btnOcistiPretraguPrisustva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOcistiPretraguPrisustvaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnPretraziPrisustvo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                        .addComponent(btnOcistiPretraguPrisustva))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbMesecPretraga, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtGodinaPretraga))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(cmbMesecPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtGodinaPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPretraziPrisustvo)
                    .addComponent(btnOcistiPretraguPrisustva))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setText("DD.MM.GGGG.");

        btnObrisiPrisustvo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnObrisiPrisustvo.setText("Obrisi prisustvo");
        btnObrisiPrisustvo.setPreferredSize(new java.awt.Dimension(96, 33));
        btnObrisiPrisustvo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiPrisustvoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlUnosPrissustvaLayout = new javax.swing.GroupLayout(pnlUnosPrissustva);
        pnlUnosPrissustva.setLayout(pnlUnosPrissustvaLayout);
        pnlUnosPrissustvaLayout.setHorizontalGroup(
            pnlUnosPrissustvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUnosPrissustvaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUnosPrissustvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlUnosPrissustvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbClanPrisustva, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlUnosPrissustvaLayout.createSequentialGroup()
                        .addGroup(pnlUnosPrissustvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnObrisiPrisustvo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUnesiPrisustvo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                            .addComponent(txtDatumPrisustvovanja, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(45, 45, 45)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlUnosPrissustvaLayout.setVerticalGroup(
            pnlUnosPrissustvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUnosPrissustvaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlUnosPrissustvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbClanPrisustva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(pnlUnosPrissustvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlUnosPrissustvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDatumPrisustvovanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlUnosPrissustvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUnesiPrisustvo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnObrisiPrisustvo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlAttendanceLayout = new javax.swing.GroupLayout(pnlAttendance);
        pnlAttendance.setLayout(pnlAttendanceLayout);
        pnlAttendanceLayout.setHorizontalGroup(
            pnlAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAttendanceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlUnosPrissustva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlAttendanceLayout.setVerticalGroup(
            pnlAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAttendanceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlUnosPrissustva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlPayments.setBackground(new java.awt.Color(255, 255, 255));

        pnlZaduzenjaClana.setBackground(new java.awt.Color(255, 255, 255));
        pnlZaduzenjaClana.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Zaduzenja clana", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 24))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Clan:");
        jLabel9.setPreferredSize(new java.awt.Dimension(0, 40));

        cmbClanClanarine.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbClanClanarine.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbClanClanarine.setPreferredSize(new java.awt.Dimension(0, 40));
        cmbClanClanarine.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbClanClanarineItemStateChanged(evt);
            }
        });

        tblClanarine.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tblClanarine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblClanarine.setRowHeight(33);
        jScrollPane2.setViewportView(tblClanarine);

        btnIzmeniZaduzenje.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnIzmeniZaduzenje.setText("Izmeni zaduzenje");
        btnIzmeniZaduzenje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniZaduzenjeActionPerformed(evt);
            }
        });

        btnObrisiZaduzenje.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnObrisiZaduzenje.setText("Obrisi zaduzenje");
        btnObrisiZaduzenje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiZaduzenjeActionPerformed(evt);
            }
        });

        pnlUnosZaduzenja.setBackground(new java.awt.Color(255, 255, 255));
        pnlUnosZaduzenja.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Unos novog zaduzenja", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Iznos:");
        jLabel10.setPreferredSize(new java.awt.Dimension(0, 40));

        txtIznos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtIznos.setPreferredSize(new java.awt.Dimension(0, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Mesec:");
        jLabel11.setPreferredSize(new java.awt.Dimension(0, 40));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Godina:");
        jLabel12.setPreferredSize(new java.awt.Dimension(0, 40));

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januar", "Februar", "Mart", "April", "Maj", "Jun", "Jul", "Avgust", "Septembar", "Oktobar", "Novembar", "Decembar" }));
        jComboBox1.setPreferredSize(new java.awt.Dimension(0, 40));

        txtGodina.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtGodina.setPreferredSize(new java.awt.Dimension(0, 40));

        btnUnosNovogZaduzenja.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnUnosNovogZaduzenja.setText("Unesi zaduzenje");
        btnUnosNovogZaduzenja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnosNovogZaduzenjaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlUnosZaduzenjaLayout = new javax.swing.GroupLayout(pnlUnosZaduzenja);
        pnlUnosZaduzenja.setLayout(pnlUnosZaduzenjaLayout);
        pnlUnosZaduzenjaLayout.setHorizontalGroup(
            pnlUnosZaduzenjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUnosZaduzenjaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUnosZaduzenjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnUnosNovogZaduzenja, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                    .addGroup(pnlUnosZaduzenjaLayout.createSequentialGroup()
                        .addGroup(pnlUnosZaduzenjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlUnosZaduzenjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIznos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, 175, Short.MAX_VALUE)
                            .addComponent(txtGodina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlUnosZaduzenjaLayout.setVerticalGroup(
            pnlUnosZaduzenjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUnosZaduzenjaLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlUnosZaduzenjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIznos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlUnosZaduzenjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlUnosZaduzenjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGodina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnUnosNovogZaduzenja)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSacuvajIzmene.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSacuvajIzmene.setText("Sacuvaj izmene");
        btnSacuvajIzmene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajIzmeneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlZaduzenjaClanaLayout = new javax.swing.GroupLayout(pnlZaduzenjaClana);
        pnlZaduzenjaClana.setLayout(pnlZaduzenjaClanaLayout);
        pnlZaduzenjaClanaLayout.setHorizontalGroup(
            pnlZaduzenjaClanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlZaduzenjaClanaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlZaduzenjaClanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(pnlZaduzenjaClanaLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbClanClanarine, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlZaduzenjaClanaLayout.createSequentialGroup()
                        .addComponent(btnIzmeniZaduzenje)
                        .addGap(18, 18, 18)
                        .addComponent(btnObrisiZaduzenje)
                        .addGap(18, 18, 18)
                        .addComponent(btnSacuvajIzmene, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pnlZaduzenjaClanaLayout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(pnlUnosZaduzenja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(462, Short.MAX_VALUE))
        );
        pnlZaduzenjaClanaLayout.setVerticalGroup(
            pnlZaduzenjaClanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlZaduzenjaClanaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnlZaduzenjaClanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbClanClanarine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlZaduzenjaClanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSacuvajIzmene, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlZaduzenjaClanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnIzmeniZaduzenje)
                        .addComponent(btnObrisiZaduzenje)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlUnosZaduzenja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout pnlPaymentsLayout = new javax.swing.GroupLayout(pnlPayments);
        pnlPayments.setLayout(pnlPaymentsLayout);
        pnlPaymentsLayout.setHorizontalGroup(
            pnlPaymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPaymentsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlZaduzenjaClana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlPaymentsLayout.setVerticalGroup(
            pnlPaymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPaymentsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlZaduzenjaClana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlTests.setBackground(new java.awt.Color(255, 255, 255));

        pnlPolaganja.setBackground(new java.awt.Color(255, 255, 255));
        pnlPolaganja.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Polaganja", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 24))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Clan:");
        jLabel13.setPreferredSize(new java.awt.Dimension(0, 40));

        cmbClanPolaganja.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbClanPolaganja.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbClanPolaganja.setPreferredSize(new java.awt.Dimension(0, 40));
        cmbClanPolaganja.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbClanPolaganjaItemStateChanged(evt);
            }
        });

        tblPolaganja.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tblPolaganja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPolaganja.setRowHeight(33);
        jScrollPane3.setViewportView(tblPolaganja);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Unos novog polaganja", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 24))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("Polaganje za pojas:");
        jLabel15.setPreferredSize(new java.awt.Dimension(0, 40));

        rbPolozenoDa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rbPolozenoDa.setText(" Da");
        rbPolozenoDa.setPreferredSize(new java.awt.Dimension(0, 40));
        rbPolozenoDa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPolozenoDaActionPerformed(evt);
            }
        });

        rbPolozenoNe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rbPolozenoNe.setText("Ne");
        rbPolozenoNe.setPreferredSize(new java.awt.Dimension(0, 40));
        rbPolozenoNe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPolozenoNeActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("Polozeno:");
        jLabel16.setPreferredSize(new java.awt.Dimension(0, 40));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setText("Datum polaganja:");
        jLabel17.setPreferredSize(new java.awt.Dimension(0, 40));

        txtDatumPolaganja.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtDatumPolaganja.setPreferredSize(new java.awt.Dimension(0, 40));

        btnUnesiNovoPolaganje.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnUnesiNovoPolaganje.setText("Unesi polaganje");
        btnUnesiNovoPolaganje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnesiNovoPolaganjeActionPerformed(evt);
            }
        });

        cmbPolaganjeZaPojas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbPolaganjeZaPojas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Beli", "Plavi", "Ljubicasti", "Braon", "Crni" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUnesiNovoPolaganje, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbPolozenoDa, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rbPolozenoNe, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtDatumPolaganja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbPolaganjeZaPojas, 0, 288, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPolaganjeZaPojas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbPolozenoNe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rbPolozenoDa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDatumPolaganja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(btnUnesiNovoPolaganje)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnIzmeniPolaganje.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnIzmeniPolaganje.setText("Izmeni polaganje");
        btnIzmeniPolaganje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniPolaganjeActionPerformed(evt);
            }
        });

        btnObrisiPolaganje.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnObrisiPolaganje.setText("Obrisi polaganje");
        btnObrisiPolaganje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiPolaganjeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPolaganjaLayout = new javax.swing.GroupLayout(pnlPolaganja);
        pnlPolaganja.setLayout(pnlPolaganjaLayout);
        pnlPolaganjaLayout.setHorizontalGroup(
            pnlPolaganjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPolaganjaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPolaganjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1118, Short.MAX_VALUE)
                    .addGroup(pnlPolaganjaLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbClanPolaganja, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlPolaganjaLayout.createSequentialGroup()
                        .addComponent(btnIzmeniPolaganje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnObrisiPolaganje)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pnlPolaganjaLayout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPolaganjaLayout.setVerticalGroup(
            pnlPolaganjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPolaganjaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlPolaganjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbClanPolaganja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlPolaganjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPolaganjaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnIzmeniPolaganje))
                    .addGroup(pnlPolaganjaLayout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(btnObrisiPolaganje)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlTestsLayout = new javax.swing.GroupLayout(pnlTests);
        pnlTests.setLayout(pnlTestsLayout);
        pnlTestsLayout.setHorizontalGroup(
            pnlTestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTestsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPolaganja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTestsLayout.setVerticalGroup(
            pnlTestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTestsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPolaganja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlRightLayout = new javax.swing.GroupLayout(pnlRight);
        pnlRight.setLayout(pnlRightLayout);
        pnlRightLayout.setHorizontalGroup(
            pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlAddMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlAttendance, javax.swing.GroupLayout.DEFAULT_SIZE, 1152, Short.MAX_VALUE))
            .addGroup(pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlPayments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlTests, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlRightLayout.setVerticalGroup(
            pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlAddMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlAttendance, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE))
            .addGroup(pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlPayments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlTests, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlTop.setBackground(new java.awt.Color(225, 127, 38));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N

        javax.swing.GroupLayout pnlTopLayout = new javax.swing.GroupLayout(pnlTop);
        pnlTop.setLayout(pnlTopLayout);
        pnlTopLayout.setHorizontalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTopLayout.createSequentialGroup()
                .addContainerGap(891, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(53, 53, 53))
        );
        pnlTopLayout.setVerticalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel14)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addComponent(pnlSideMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(pnlSideMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addComponent(pnlTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        setHomePnl();
    }//GEN-LAST:event_btnHomeActionPerformed
    

    private void btnMembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMembersActionPerformed
        setAddMemberPnl();
        setTableClanovi();
    }//GEN-LAST:event_btnMembersActionPerformed
    

    private void btnAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttendanceActionPerformed
        setAttendancePnl();
        popuniClanove(cmbClanPrisustva);
    }//GEN-LAST:event_btnAttendanceActionPerformed
    

    private void btnPaymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentsActionPerformed
        setPaymentsPnl();
        popuniClanove(cmbClanClanarine);
    }//GEN-LAST:event_btnPaymentsActionPerformed
    

    private void btnTestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestsActionPerformed
        setTestsPnl();
        popuniClanove(cmbClanPolaganja);
    }//GEN-LAST:event_btnTestsActionPerformed

    // CLAN - UNOS
    private void btnDodajClanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajClanaActionPerformed
        try {
            
            Clan clan = new Clan(0, txtIme.getText().trim(), txtPrezime.getText().trim(), (String) cmbPol.getSelectedItem(), txtTelefon.getText().trim(), txtAdresa.getText().trim(), (String) cmbPojas.getSelectedItem());
            
            Controller.getInstance().addClan(clan);
            
            setTableClanovi();
            
            JOptionPane.showMessageDialog(this, "Uspešno unet novi clan!");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            //e.printStackTrace();
        }
    }//GEN-LAST:event_btnDodajClanaActionPerformed

    // PRISUSTVO - UNOS
    private void btnUnesiPrisustvoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnesiPrisustvoActionPerformed
        
        try {
            
            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy.");
            Date datum = sdf.parse(txtDatumPrisustvovanja.getText().trim());
            
            Clan clan = (Clan) cmbClanPrisustva.getSelectedItem();
            int index = cmbClanPrisustva.getSelectedIndex();
            
            Prisustvo prisustvo = new Prisustvo(0, datum, clan.getClanID());
            
            Controller.getInstance().addPrisustvo(prisustvo);
            
            popuniClanove(cmbClanPrisustva);
            cmbClanPrisustva.setSelectedIndex(index);
            
            JOptionPane.showMessageDialog(this, "Uspešno uneto prisustvo člana!");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            //e.printStackTrace();
        }
    }//GEN-LAST:event_btnUnesiPrisustvoActionPerformed

    //cmb za Prisustva
    private void cmbClanPrisustvaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbClanPrisustvaItemStateChanged
        
        ListModelPrisustva lm = (ListModelPrisustva) listPrisustva.getModel();
        Clan clan = (Clan) cmbClanPrisustva.getSelectedItem();
        if (clan != null) {
            if (clan.getPrisustva() != null) {
                lm.setPrisustva(clan.getPrisustva());
            }
        }
    }//GEN-LAST:event_cmbClanPrisustvaItemStateChanged

    // CLANARINA - IZMENA - JDialog
    private void btnIzmeniZaduzenjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniZaduzenjeActionPerformed
        
        int row = tblClanarine.getSelectedRow();
        if (row != -1) {
            TableModelClanarine tm = (TableModelClanarine) tblClanarine.getModel();
            Clanarina c = tm.vratiClanarinu(row);
            new FrmIzmeniZaduzenje(this, true, c).setVisible(true);
        }
    }//GEN-LAST:event_btnIzmeniZaduzenjeActionPerformed

    // CLANARINA - BRISANJE
    private void btnObrisiZaduzenjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiZaduzenjeActionPerformed
        int row = tblClanarine.getSelectedRow();
        int index = cmbClanClanarine.getSelectedIndex();
        if (row != -1) {
            try {
                TableModelClanarine tm = (TableModelClanarine) tblClanarine.getModel();
                Clanarina clanarina = tm.vratiClanarinu(row);
                zaDelete.add(clanarina);
                tm.obrisiClanarinu(row);

                //Clanarina clanarinaBrisanje = tm.vratiClanarinu(row);
                //Controller.getInstance().deleteClanarina(clanarinaBrisanje);
                //popuniClanove(cmbClanClanarine);
                //cmbClanClanarine.setSelectedIndex(index);
                JOptionPane.showMessageDialog(this, "Uspešno obrisano zaduženje člana!");
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
                //ex.printStackTrace();
            }
            
        }
    }//GEN-LAST:event_btnObrisiZaduzenjeActionPerformed

    // CLANARINA - UNOS
    private void btnUnosNovogZaduzenjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnosNovogZaduzenjaActionPerformed
        
        try {
            
            Clan clan = (Clan) cmbClanClanarine.getSelectedItem();
            int index = cmbClanClanarine.getSelectedIndex();
            
            Clanarina clanarina = new Clanarina();
            
            clanarina.setIznos(new BigDecimal(txtIznos.getText().trim()));
            clanarina.setZaMesec((String) jComboBox1.getSelectedItem());
            clanarina.setZaGodinu(Integer.parseInt(txtGodina.getText().trim()));
            clanarina.setClanID(clan.getClanID());
            
            TableModelClanarine tm = (TableModelClanarine) tblClanarine.getModel();
            tm.dodajClanarinu(clanarina);
            zaAdd.add(clanarina);

            //Controller.getInstance().addClanarina(clanarina);
            //popuniClanove(cmbClanClanarine);
            //cmbClanClanarine.setSelectedIndex(index);
            JOptionPane.showMessageDialog(this, "Uspešno uneto zaduženje člana!");
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Iznos i godina moraju biti brojevi!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnUnosNovogZaduzenjaActionPerformed

    //cmb za Clanarine
    private void cmbClanClanarineItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbClanClanarineItemStateChanged
        
        TableModelClanarine tm = (TableModelClanarine) tblClanarine.getModel();
        Clan clan = (Clan) cmbClanClanarine.getSelectedItem();
        if (clan != null) {
            if (clan.getClanarine() != null) {
                tm.setClanarine(clan.getClanarine());
            }
        }
        
        zaEdit = new ArrayList<>();
        zaDelete = new ArrayList<>();
        zaAdd = new ArrayList<>();

    }//GEN-LAST:event_cmbClanClanarineItemStateChanged

    // cmb za Polaganja
    private void cmbClanPolaganjaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbClanPolaganjaItemStateChanged
        
        TableModelPolaganja tm = (TableModelPolaganja) tblPolaganja.getModel();
        Clan clan = (Clan) cmbClanPolaganja.getSelectedItem();
        if (clan != null) {
            if (clan.getPolaganja() != null) {
                tm.setPolaganja(clan.getPolaganja());
            }
        }
    }//GEN-LAST:event_cmbClanPolaganjaItemStateChanged

    // PRISUSTVO - PRETRAZI (PO MESECU I GODINI)
    private void btnPretraziPrisustvoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziPrisustvoActionPerformed
        try {
            
            Clan c = (Clan) cmbClanPrisustva.getSelectedItem();
            int mesec = cmbMesecPretraga.getSelectedIndex();
            mesec += 1;
            
            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy.");
            String datumStr = "01." + mesec + "." + txtGodinaPretraga.getText().trim() + ".";
            Date datum = sdf.parse(datumStr);
            
            Prisustvo prisustvo = new Prisustvo(0, datum, c.getClanID());
            
            List< Prisustvo> prisustva = Controller.getInstance().getAllByCriteriaPrisustvoClanaPoDatumu(prisustvo);
            
            ListModelPrisustva lm = (ListModelPrisustva) listPrisustva.getModel();
            lm.setPrisustva(prisustva);
            
            JOptionPane.showMessageDialog(this, "Uspešno pretražena prisustva člana!");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            //e.printStackTrace();
        }
    }//GEN-LAST:event_btnPretraziPrisustvoActionPerformed

    // PRISUSTVO - CISCENJE PRETRAGE - prikaz svih prisustva clana
    private void btnOcistiPretraguPrisustvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOcistiPretraguPrisustvaActionPerformed
        
        cmbMesecPretraga.setSelectedIndex(0);
        txtGodinaPretraga.setText("");
        
        ListModelPrisustva lm = (ListModelPrisustva) listPrisustva.getModel();
        Clan clan = (Clan) cmbClanPrisustva.getSelectedItem();
        if (clan != null) {
            if (clan.getPrisustva() != null) {
                lm.setPrisustva(clan.getPrisustva());
            }
        }
    }//GEN-LAST:event_btnOcistiPretraguPrisustvaActionPerformed

    // POLAGANJE
    private void rbPolozenoDaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPolozenoDaActionPerformed
        rbPolozenoDa.setSelected(true);
        rbPolozenoNe.setSelected(false);
    }//GEN-LAST:event_rbPolozenoDaActionPerformed

    // POLAGANJE
    private void rbPolozenoNeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPolozenoNeActionPerformed
        rbPolozenoNe.setSelected(true);
        rbPolozenoDa.setSelected(false);
    }//GEN-LAST:event_rbPolozenoNeActionPerformed

    //POLAGANJE - UNOS
    private void btnUnesiNovoPolaganjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnesiNovoPolaganjeActionPerformed
        try {
            
            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy.");
            Date datumPolaganja = sdf.parse(txtDatumPolaganja.getText().trim());
            
            Clan clan = (Clan) cmbClanPolaganja.getSelectedItem();
            int index = cmbClanPolaganja.getSelectedIndex();
            
            Polaganje polaganje = new Polaganje(0, (String) cmbPolaganjeZaPojas.getSelectedItem(), rbPolozenoDa.isSelected(), datumPolaganja, clan.getClanID());
            
            Controller.getInstance().addPolaganje(polaganje);
            
            popuniClanove(cmbClanPolaganja);
            cmbClanPolaganja.setSelectedIndex(index);
            
            JOptionPane.showMessageDialog(this, "Uspešno uneto polaganje člana!");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            //e.printStackTrace();
        }
    }//GEN-LAST:event_btnUnesiNovoPolaganjeActionPerformed

    // CLAN - IZMENA - JDialog
    private void btnIzmeniClanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniClanaActionPerformed
        int row = tblClanovi.getSelectedRow();
        if (row != -1) {
            TableModelClanovi tm = (TableModelClanovi) tblClanovi.getModel();
            Clan clan = tm.vratiClana(row);
            
            new FrmIzmeniClana(this, true, clan).setVisible(true);
        }
    }//GEN-LAST:event_btnIzmeniClanaActionPerformed

    // CLAN - BRISANJE
    private void btnObrisiClanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiClanaActionPerformed
        
        int row = tblClanovi.getSelectedRow();
        if (row != -1) {
            try {
                TableModelClanovi tm = (TableModelClanovi) tblClanovi.getModel();
                Clan clanBrisanje = tm.vratiClana(row);
                
                Controller.getInstance().deleteClan(clanBrisanje);
                
                setTableClanovi();
                
                JOptionPane.showMessageDialog(this, "Uspešno obrisan član!");
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
                //ex.printStackTrace();
            }
            
        }

    }//GEN-LAST:event_btnObrisiClanaActionPerformed

    // PRISUSTVO - BRISANJE
    private void btnObrisiPrisustvoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiPrisustvoActionPerformed
        
        int index = listPrisustva.getSelectedIndex();
        if (index != -1) {
            try {
                ListModelPrisustva lm = (ListModelPrisustva) listPrisustva.getModel();
                Prisustvo prisustvoBrisanje = lm.getPrisustvo(index);
                
                Controller.getInstance().deletePrisustvo(prisustvoBrisanje);
                
                int clanIndex = cmbClanPrisustva.getSelectedIndex();
                popuniClanove(cmbClanPrisustva);
                cmbClanPrisustva.setSelectedIndex(clanIndex);
                
                JOptionPane.showMessageDialog(this, "Uspešno obrisano prisustvo člana!");
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
                //ex.printStackTrace();
            }
        }
        

    }//GEN-LAST:event_btnObrisiPrisustvoActionPerformed

    // POLAGANJE - IZMENA - JDialog
    private void btnIzmeniPolaganjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniPolaganjeActionPerformed
        int row = tblPolaganja.getSelectedRow();
        if (row != -1) {
            TableModelPolaganja tm = (TableModelPolaganja) tblPolaganja.getModel();
            Polaganje polaganje = tm.vratiPolaganje(row);
            
            new FrmIzmeniPolaganje(this, true, polaganje).setVisible(true);
        }

    }//GEN-LAST:event_btnIzmeniPolaganjeActionPerformed

    //POLAGANJE - BRISANJE
    private void btnObrisiPolaganjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiPolaganjeActionPerformed
        
        int row = tblPolaganja.getSelectedRow();
        if (row != -1) {
            try {
                TableModelPolaganja tm = (TableModelPolaganja) tblPolaganja.getModel();
                Polaganje polaganjeBrisanje = tm.vratiPolaganje(row);
                
                Controller.getInstance().deletePolaganje(polaganjeBrisanje);
                
                int clanIndex = cmbClanPolaganja.getSelectedIndex();
                popuniClanove(cmbClanPolaganja);
                cmbClanPolaganja.setSelectedIndex(clanIndex);
                
                JOptionPane.showMessageDialog(this, "Uspešno obrisano polaganje člana!");
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
                //ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnObrisiPolaganjeActionPerformed

    private void btnSacuvajIzmeneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajIzmeneActionPerformed
        
        try {
            IzmenaClanarina izmena = new IzmenaClanarina(zaAdd, zaEdit, zaDelete);
            
            Controller.getInstance().changeAllClanarina(izmena);
            
            int index = cmbClanClanarine.getSelectedIndex();
            popuniClanove(cmbClanClanarine);
            cmbClanClanarine.setSelectedIndex(index);
            
            JOptionPane.showMessageDialog(this, "Uspešno sačuvane izmene!");
            
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnSacuvajIzmeneActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAttendance;
    private javax.swing.JButton btnDodajClana;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnIzmeniClana;
    private javax.swing.JButton btnIzmeniPolaganje;
    private javax.swing.JButton btnIzmeniZaduzenje;
    private javax.swing.JButton btnMembers;
    private javax.swing.JButton btnObrisiClana;
    private javax.swing.JButton btnObrisiPolaganje;
    private javax.swing.JButton btnObrisiPrisustvo;
    private javax.swing.JButton btnObrisiZaduzenje;
    private javax.swing.JButton btnOcistiPretraguPrisustva;
    private javax.swing.JButton btnPayments;
    private javax.swing.JButton btnPretraziPrisustvo;
    private javax.swing.JButton btnSacuvajIzmene;
    private javax.swing.JButton btnTests;
    private javax.swing.JButton btnUnesiNovoPolaganje;
    private javax.swing.JButton btnUnesiPrisustvo;
    private javax.swing.JButton btnUnosNovogZaduzenja;
    private javax.swing.JComboBox<String> cmbClanClanarine;
    private javax.swing.JComboBox<String> cmbClanPolaganja;
    private javax.swing.JComboBox cmbClanPrisustva;
    private javax.swing.JComboBox cmbMesecPretraga;
    private javax.swing.JComboBox<String> cmbPojas;
    private javax.swing.JComboBox<String> cmbPol;
    private javax.swing.JComboBox<String> cmbPolaganjeZaPojas;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblFigures;
    private javax.swing.JList listPrisustva;
    private javax.swing.JPanel pnlAddMember;
    private javax.swing.JPanel pnlAttendance;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlPayments;
    private javax.swing.JPanel pnlPolaganja;
    private javax.swing.JPanel pnlRight;
    private javax.swing.JPanel pnlSideMenu;
    private javax.swing.JPanel pnlTests;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JPanel pnlUnosClana;
    private javax.swing.JPanel pnlUnosPrissustva;
    private javax.swing.JPanel pnlUnosZaduzenja;
    private javax.swing.JPanel pnlZaduzenjaClana;
    private javax.swing.JRadioButton rbPolozenoDa;
    private javax.swing.JRadioButton rbPolozenoNe;
    private javax.swing.JTable tblClanarine;
    private javax.swing.JTable tblClanovi;
    private javax.swing.JTable tblPolaganja;
    private javax.swing.JTextField txtAdresa;
    private javax.swing.JTextField txtDatumPolaganja;
    private javax.swing.JTextField txtDatumPrisustvovanja;
    private javax.swing.JTextField txtGodina;
    private javax.swing.JTextField txtGodinaPretraga;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtIznos;
    private javax.swing.JTextField txtPrezime;
    private javax.swing.JTextField txtTelefon;
    // End of variables declaration//GEN-END:variables

    private void setHomePnl() {
        pnlHome.setVisible(true);
        pnlAddMember.setVisible(false);
        pnlAttendance.setVisible(false);
        pnlPayments.setVisible(false);
        pnlTests.setVisible(false);
    }
    
    private void setAddMemberPnl() {
        pnlHome.setVisible(false);
        pnlAddMember.setVisible(true);
        pnlAttendance.setVisible(false);
        pnlPayments.setVisible(false);
        pnlTests.setVisible(false);
    }
    
    private void setAttendancePnl() {
        pnlHome.setVisible(false);
        pnlAddMember.setVisible(false);
        pnlAttendance.setVisible(true);
        pnlPayments.setVisible(false);
        pnlTests.setVisible(false);
    }
    
    private void setPaymentsPnl() {
        pnlHome.setVisible(false);
        pnlAddMember.setVisible(false);
        pnlAttendance.setVisible(false);
        pnlPayments.setVisible(true);
        pnlTests.setVisible(false);
    }
    
    private void setTestsPnl() {
        pnlHome.setVisible(false);
        pnlAddMember.setVisible(false);
        pnlAttendance.setVisible(false);
        pnlPayments.setVisible(false);
        pnlTests.setVisible(true);
        
    }
    
    private void popuniClanove(JComboBox cmb) {
        
        try {
            List<Clan> clanovi = Controller.getInstance().getAllClan();
            
            cmb.removeAllItems();
            
            for (Clan clan : clanovi) {
                cmb.addItem(clan);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            ex.printStackTrace();
        }
    }
    
    void izmenaClanarine(Clanarina clanarina) {
//        int index = cmbClanClanarine.getSelectedIndex();
//        popuniClanove(cmbClanClanarine);
//        cmbClanClanarine.setSelectedIndex(index);

        zaEdit.add(clanarina);
        TableModelClanarine tm = (TableModelClanarine) tblClanarine.getModel();
        tm.izmenaClanarine(clanarina);
        
    }
    
    public void setTableClanovi() {
        try {
            TableModelClanovi tm = (TableModelClanovi) tblClanovi.getModel();
            
            List<Clan> clanovi = Controller.getInstance().getAllClan();
            tm.setClanovi(clanovi);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            ex.printStackTrace();
        }
    }
    
    void izmenaPolaganja() {
        int index = cmbClanPolaganja.getSelectedIndex();
        popuniClanove(cmbClanPolaganja);
        cmbClanPolaganja.setSelectedIndex(index);
    }
    
}
